POST  http://localhost/api/v1/register_work_time
Content-Type: application/json

{
  "employeeUuid": "1834fbb4-0557-45e5-8b5f-9f704bd8cd32",
  "startTime": "08.03.2025 08:00",
  "endTime": "08.03.2025 14:00"
}